version: "3.7"

#################-POSTGRES-##########################
postgres:
  image: docker.io/bitnami/postgresql:latest
  volumes:
    - ./Database/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  environment:
    - POSTGRESQL_USERNAME=root
    - POSTGRESQL_DATABASE=root
    - "ALLOW_EMPTY_PASSWORD=yes"
  ports:
    - "5432:5432"
###################-PG_ADMIN-##########################
pgadmin:
  image: "dpage/pgadmin4"
  environment:
    PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
    PGADMIN_DEFAULT_PASSWORD: "admin"
  ports:
    - "80:80"
  depends_on:
    - postgres
  logging:
    driver: none
